[package]
name = "biotoxin495/pluginuitoasts"
description = "a small, self-contained toast notification utility built specifically for Roblox Studio plugins."
version = "1.0.0"
license = "MIT"
authors = ["biotoxin495"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/biotoxin495/PluginUIToasts"

exclude = [
	"examples",
	"docs",
	".github",
	"*.rbxl",
	"*.rbxlx",
]